export const storageDataFiles = {
  'album-arts': [
    'ys-i-and-ii-chronicles-original-soundtrack',
    'ys-ix-monstrum-nox-original-soundtrack',
    'ys-origin-original-sound-track',
  ],
  'character-avatars': [
    'adol-christin',
    'aprilis',
    'dogi',
    'feena',
    'hugo-fact',
    'krysha-pendleton',
    'reah',
    'toal-fact',
    'yunica-tovah',
  ],
  'character-gallery': [
    'adol-christin/7db99fcb-3ed5-473a-beae-8143ffd10cae',
    'hugo-fact/44e46717-052c-46a7-a7bb-dba56b8185b1',
    'yunica-tovah/71cc978a-b66f-421c-b247-42b8b7379e1f',
  ],
  characters: [
    'adol-christin',
    'aprilis',
    'dogi',
    'feena',
    'hugo-fact',
    'krysha-pendleton',
    'reah',
    'toal-fact',
    'yunica-tovah',
  ],
  'game-banners': [
    'ys-i-ancient-ys-vanished-omen',
    'ys-i-ancient-ys-vanished-the-final-chapter',
    'ys-iii-wanderers-from-ys',
    'ys-iv-mask-of-the-sun',
    'ys-iv-the-dawn-of-ys',
    'ys-ix-monstrum-nox',
    'ys-memories-of-celceta',
    'ys-origin',
    'ys-seven',
    'ys-the-oath-in-felghana',
    'ys-v-kefin-lost-kingdom-of-sand',
    'ys-vi-the-ark-of-napishtim',
    'ys-viii-lacrimosa-of-dana',
    'ys-vs-trails-in-the-sky-alternative-saga',
    'ys-x-nordics',
  ],
  'game-covers': [
    'ys-i-ancient-ys-vanished-omen',
    'ys-i-ancient-ys-vanished-the-final-chapter',
    'ys-iii-wanderers-from-ys',
    'ys-iv-mask-of-the-sun',
    'ys-iv-the-dawn-of-ys',
    'ys-ix-monstrum-nox',
    'ys-memories-of-celceta',
    'ys-origin',
    'ys-seven',
    'ys-the-oath-in-felghana',
    'ys-v-kefin-lost-kingdom-of-sand',
    'ys-vi-the-ark-of-napishtim',
    'ys-viii-lacrimosa-of-dana',
    'ys-vs-trails-in-the-sky-alternative-saga',
    'ys-x-nordics',
  ],
  'staff-avatars': ['yukihiro-jindo'],
};
